### ISSUE TITLE
[Feature Request] Separate Menu Per Content Object

### ISSUE THREAD

**Issue by Janooba** [kunjsharma/adapt-inline-menu#1]
Currently this component builds a single menu for the entire course. If you have more than one contentObject, it shares the same menu. Could we get a way to have different menu's display for each contentObject?

This would require the menu to refresh/rebuild when the location changes. I've tried implementing this myself, but I couldn't get it working. My Adapt knowledge is too limited.

Something like this for the JSON could work:
```json
"_modules": [
    {
        "id": "id of module",
        "_items": [
            {
                // Items
            }
        ]
    }
]
```

**Comment by kunjsharma** [comment]
Hi Janooba, thanks for 'feature request', will queue and try in next versions. Please appreciate if you find it helpful.
